# Generated by Django 4.1 on 2022-09-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('task', models.CharField(max_length=1000)),
                ('review', models.BooleanField(default=False)),
            ],
        ),
    ]
